version: '3'

services:
   app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_USER=lolkekcheburek
      - MINIO_PASSWORD=lolkekcheburek
    depends_on:
      - minio

   minio:
    image: minio/minio:latest
    command: minio server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=lolkekcheburek
      - MINIO_ROOT_PASSWORD=lolkekcheburek
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data




